### ISSUE TITLE
Needs TOOLCHAINS set to build properly ..

### ISSUE THREAD

**Issue by seclorum** [NeoTeo/IpfsIosAppExample#1]
Just FYI, as of Carthage 0.18.1 and with XCode8 on the machine, this is currently needed in order to build the Carthage dependencies:

    $ TOOLCHAINS=com.apple.dt.toolchain.Swift_2_3 carthage update

**Comment by NeoTeo** [comment]
Hi seclorum. Thanks for the heads up. The master branch should now be using the correct libs upstream.
