### ISSUE TITLE
`netServiceDidResolveAddress` never gets called

### ISSUE THREAD

**Issue by jorgej-ramos** [NeoTeo/IpfsIosAppExample#2]
Hi, I'm testing IPFS for iOS and I've found your example repo. I'm trying to execute it on an iPhone 6 running iOS 11. It compiles, install, run the IPA and start resolving IPFS service but `netServiceDidResolveAddress` never get called. 

Maybe I'm not understanding the purpose of the `swift-ipfs-api`. I'm trying to run a full working IPFS node on an iOS device, the same way I can run a node on my MacBook terminal. Is this a correct approach? Or this repo is no longer maintained?

Thank you for your time

**Comment by NeoTeo** [comment]
Hi Jorge.

As you are hinting at, your approach is not correct. The project is a native API lib that requires an existing node to be running on the network.

Best,
Teo

**Comment by jorgej-ramos** [comment]
Thank you so much and sorry for my misunderstanding
