### ISSUE TITLE
is it possible to connect to localhost from simulator?

### ISSUE THREAD

**Issue by johndpope** [NeoTeo/IpfsIosAppExample#3]
class IpfsNodeDiscovery : NSObject, NetServiceBrowserDelegate, NetServiceDelegate {
    let DOMAIN = "local"
//    let SERVICE_TYPE = "_services._dns-sd._udp."//"_airplay._tcp."
    let SERVICE_TYPE = "_ipfs-discovery._udp."
//    let SERVICE_TYPE = "_ipfs._tcp."
//    let SERVICE_TYPE = "_1password4._tcp."
    let domainBrowser: NetServiceBrowser
    var active_service: NetService?
    var active_handler: ((String) -> ())?
    var node_address: String?

ipfs daemon is running fine. 

nitializing daemon...
Swarm listening on /ip4/10.106.30.113/tcp/4001
Swarm listening on /ip4/127.0.0.1/tcp/4001
Swarm listening on /ip6/::1/tcp/4001
Swarm listening on /p2p-circuit/ipfs/QmPGh4BgmrFqBcqNDa1kLww8nFsjhw2MZzjSiokvrXekEM
Swarm announcing /ip4/10.106.30.113/tcp/4001
Swarm announcing /ip4/127.0.0.1/tcp/4001
Swarm announcing /ip6/::1/tcp/4001
API server listening on /ip4/127.0.0.1/tcp/5001
Gateway (readonly) server listening on /ip4/127.0.0.1/tcp/8080
Daemon is ready
16:56:15.791 ERROR ipns-repub: Republisher failed to republish: failed to find any peer in table core.go:518
17:01:15.787 ERROR ipns-repub: Republisher failed to republish: failed to find any peer in table core.go:518
17:06:15.785 ERROR ipns-repub: Republisher failed to republish: failed to find any peer in table core.go:518
17:11:15.783 ERROR ipns-repub: Republisher failed to republish: failed to find any peer in table core.go:518

**Comment by johndpope** [comment]
it worked when I jumped off the network

Bingo Optional([16 bytes, 28 bytes])
127.0.0.1
fe80::1

**Comment by chinesebug** [comment]
Hi @johndpope , is DOMAIN the only thing needed to change for this? I changed it to local. And typed in ipfs daemon in terminal and saw its ready. But I only got searching in the simulator. The output are below
```
going...
Service: <NSNetService 0x60000303b7c0> local. _ipfs-discovery._udp. QmbmU66MaWrQprDqTiRXAffkK87p5aFgrLPJ9frzQqQufL -1
name: QmbmU66MaWrQprDqTiRXAffkK87p5aFgrLPJ9frzQqQufL
type: _ipfs-discovery._udp.
comparing _ipfs-discovery._udp. with _ipfs-discovery._udp.
success
nil
Resolving...
Bingo Optional([16 bytes, 16 bytes, 28 bytes])
127.0.0.1
stop
Handler received 192.168.1.195
HttpIo receiveFrom url is https://192.168.1.195:5001/api/v0/id
2019-05-02 22:53:28.099202-0700 IpfsIosApp[6734:238617] [] nw_socket_handle_socket_event [C1:3] Socket SO_ERROR [61: Connection refused]
2019-05-02 22:53:28.099542-0700 IpfsIosApp[6734:238617] [BoringSSL] nw_protocol_boringssl_error(1584) [0x7fdcace1de10] Lower protocol stack error: 61
2019-05-02 22:53:28.099944-0700 IpfsIosApp[6734:238617] [BoringSSL] nw_protocol_boringssl_handshake_negotiate_proceed(480) [0x7fdcace1de10] Handshake failed. Disconnecting the session
2019-05-02 22:53:28.103936-0700 IpfsIosApp[6734:238617] TIC TCP Conn Failed [1:0x600000570840]: 1:61 Err(61)
2019-05-02 22:53:28.107693-0700 IpfsIosApp[6734:238617] Task <EA9716E4-56C1-4188-A1F2-153E34BBF347>.<1> HTTP load failed (error code: -1004 [1:61])
2019-05-02 22:53:28.108068-0700 IpfsIosApp[6734:236584] Task <EA9716E4-56C1-4188-A1F2-153E34BBF347>.<1> finished with error - code: -1004
Error  transmissionError("Could not connect to the server.") in completionHandler passed to fetchData
```

**Comment by johndpope** [comment]
It’s been a while, from my notes, it seems like I had to disconnect from WiFi for things to see each other.
