### ISSUE TITLE
enhancement - add files from app to existing ipfs node.

### ISSUE THREAD

**Issue by johndpope** [NeoTeo/IpfsIosAppExample#4]

**Comment by johndpope** [comment]
reference 
https://raw.githubusercontent.com/provivus/IpfsKit/bffb1dc48294e7f2745d61f132025fbe63dbc9a6/IpfsKit/IpfsClient.swift

**Comment by NeoTeo** [comment]
Not sure what the issue is here. This is simply an example project to show how to use the Swift IPFS API from an iOS app.

**Comment by johndpope** [comment]
Would you prefer I close this ticket and open up on NeoTeo/swift-ipfs-api ?
 basically need to be able to upload files to ipfs from iphone app and get corresponding hash.

**Comment by NeoTeo** [comment]
Swift-ipfs-api provides the api to upload files but you need to write the application that uses the api yourself.

**Comment by johndpope** [comment]
that's exactly why this is an enhancement ticket to this example project to showcase this capability. 
I'm happy to do the work. heavy lifting already done here
https://gist.github.com/johndpope/32434dcce3b485775c8766928e8c333d

**Comment by NeoTeo** [comment]
Thank you, but I want to keep this as a minimal example for people who have problems getting started. 
I encourage you to complete your application and I could link to it as a "further exercise/more advanced" example.
:) Teo

**Comment by johndpope** [comment]
I agree the promisekit stuff makes too complex and doesn't need to bog down this sample.
I managed to simplify to this - might help to add a callback in the client putBytes method upstream.
eg. 
```swift
client?.putBytes(bytes: data.bytes() onSuccess:{
    print("done")
})
```


 ```swift
 let client = IpfsClient(ipfsHost: theIp)
                client?.ipfsApi = api

                if let theImage = UIImage(named: "ok"){
                    if let data = UIImagePNGRepresentation(theImage){
                        print("uploading...")
                       client?.putBytes(bytes: data.bytes())
                    }
                    
                }
```
